services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    environment:
      DB_SERVER_HOST: "db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
    depends_on:
      - db
    restart: always

  zabbixweb:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    environment:
      DB_SERVER_HOST: "db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: "Europe/Moscow"
    depends_on:
      - db
      - zabbix-server
    ports:
      - "8080:8080"
    restart: always