services:
  bind:
    image: dhxgc/dns-server:1.0
    network_mode: host
    volumes:
      - ./dns-config:/etc/bind
      - ./resolv.conf:/etc/resolv.conf
      - bind-cache:/var/cache/bind
      - bind-lib:/var/lib/bind
      - bind-log:/var/log/bind
    restart: always

volumes:
  bind-cache:
  bind-lib:
  bind-log: