services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: adminer
      MYSQL_DATABASE: adminer
      MYSQL_USER: adminer
      MYSQL_PASSWORD: adminer
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - db_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge